version: "3.9"
services:
  hydrotek-backend:
    container_name: hydrotek-backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - ${NEST_PORT}:3000
    networks:
      - hydrotek
networks:
   hydrotek:
