version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=hydrotek-db
    ports:
      - 100:5432
    networks:
      - hydrotek
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./db-data-backup:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d hydrotek-db -h postgres -p 5432"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
  frontend:
    build:
      context: ../hydrotek-frontend
      dockerfile: Dockerfile
    env_file:
      - ../hydrotek-frontend/.env
    ports:
      - 50:80
    networks:
      - hydrotek
    depends_on:
      - backend
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 10:3000
    networks:
      - hydrotek
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
networks:
   hydrotek:
