version: "3"
services:
  hydrotek-backend:
    container_name: ${NEST_CONTAINER_NAME}
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - ${NEST_PORT}:3000
    networks:
      - hydrotek
networks:
   hydrotek:
