-- DropIndex
DROP INDEX "Order_fresaId_key";

-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "subtotal" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "type" TEXT DEFAULT 'TEMPORAL',
ALTER COLUMN "userId" SET DEFAULT '',
ALTER COLUMN "email" SET DEFAULT '',
ALTER COLUMN "name" SET DEFAULT '',
ALTER COLUMN "totalPrice" SET DEFAULT 0,
ALTER COLUMN "fresaId" SET DEFAULT '000000';
